// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gostart/internal/dao/model"
)

func newPlatform(db *gorm.DB, opts ...gen.DOOption) platform {
	_platform := platform{}

	_platform.platformDo.IWithDO = gen.WithDOFunc[IPlatformDo](_platform.platformDo.withDO)

	_platform.platformDo.UseDB(db, opts...)
	_platform.platformDo.UseModel(&model.Platform{})

	tableName := _platform.platformDo.TableName()
	_platform.ALL = field.NewAsterisk(tableName)
	_platform.ID = field.NewInt32(tableName, "id")
	_platform.Name = field.NewString(tableName, "name")
	_platform.Code = field.NewString(tableName, "code")

	_platform.fillFieldMap()

	return _platform
}

type platform struct {
	platformDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String
	Code field.String

	fieldMap map[string]field.Expr
}

func (p platform) Table(newTableName string) *platform {
	p.platformDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p platform) As(alias string) *platform {
	p.platformDo.DO = *(p.platformDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *platform) updateTableName(table string) *platform {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Name = field.NewString(table, "name")
	p.Code = field.NewString(table, "code")

	p.fillFieldMap()

	return p
}

func (p *platform) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *platform) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["code"] = p.Code
}

func (p platform) clone(db *gorm.DB) platform {
	p.platformDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p platform) replaceDB(db *gorm.DB) platform {
	p.platformDo.ReplaceDB(db)
	return p
}

type platformDo struct {
	gen.GenericsDo[IPlatformDo, *model.Platform]
}
type IPlatformDo interface {
	gen.IGenericsDo[IPlatformDo, *model.Platform]
}

func (p *platformDo) withDO(do gen.Dao) IPlatformDo {
	_r := &platformDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IPlatformDo](p.withDO)
	return _r
}
