// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gostart/internal/dao/model"
)

func newStreamerOnline(db *gorm.DB, opts ...gen.DOOption) streamerOnline {
	_streamerOnline := streamerOnline{}

	_streamerOnline.streamerOnlineDo.IWithDO = gen.WithDOFunc[IStreamerOnlineDo](_streamerOnline.streamerOnlineDo.withDO)

	_streamerOnline.streamerOnlineDo.UseDB(db, opts...)
	_streamerOnline.streamerOnlineDo.UseModel(&model.StreamerOnline{})

	tableName := _streamerOnline.streamerOnlineDo.TableName()
	_streamerOnline.ALL = field.NewAsterisk(tableName)
	_streamerOnline.ID = field.NewInt32(tableName, "id")
	_streamerOnline.Title = field.NewString(tableName, "title")
	_streamerOnline.Img = field.NewString(tableName, "img")
	_streamerOnline.Address = field.NewString(tableName, "address")
	_streamerOnline.PlatformID = field.NewInt32(tableName, "platform_id")

	_streamerOnline.fillFieldMap()

	return _streamerOnline
}

type streamerOnline struct {
	streamerOnlineDo

	ALL        field.Asterisk
	ID         field.Int32
	Title      field.String
	Img        field.String
	Address    field.String
	PlatformID field.Int32

	fieldMap map[string]field.Expr
}

func (s streamerOnline) Table(newTableName string) *streamerOnline {
	s.streamerOnlineDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s streamerOnline) As(alias string) *streamerOnline {
	s.streamerOnlineDo.DO = *(s.streamerOnlineDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *streamerOnline) updateTableName(table string) *streamerOnline {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Title = field.NewString(table, "title")
	s.Img = field.NewString(table, "img")
	s.Address = field.NewString(table, "address")
	s.PlatformID = field.NewInt32(table, "platform_id")

	s.fillFieldMap()

	return s
}

func (s *streamerOnline) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *streamerOnline) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["title"] = s.Title
	s.fieldMap["img"] = s.Img
	s.fieldMap["address"] = s.Address
	s.fieldMap["platform_id"] = s.PlatformID
}

func (s streamerOnline) clone(db *gorm.DB) streamerOnline {
	s.streamerOnlineDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s streamerOnline) replaceDB(db *gorm.DB) streamerOnline {
	s.streamerOnlineDo.ReplaceDB(db)
	return s
}

type streamerOnlineDo struct {
	gen.GenericsDo[IStreamerOnlineDo, *model.StreamerOnline]
}
type IStreamerOnlineDo interface {
	gen.IGenericsDo[IStreamerOnlineDo, *model.StreamerOnline]
}

func (s *streamerOnlineDo) withDO(do gen.Dao) IStreamerOnlineDo {
	_r := &streamerOnlineDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IStreamerOnlineDo](s.withDO)
	return _r
}
