// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlatform = "platform"

// Platform mapped from table <platform>
type Platform struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Code string `gorm:"column:code" json:"code"`
}

// TableName Platform's table name
func (*Platform) TableName() string {
	return TableNamePlatform
}
