// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStreamerOnline = "streamer_online"

// StreamerOnline mapped from table <streamer_online>
type StreamerOnline struct {
	ID         int32  `gorm:"column:id;primaryKey" json:"id"`
	Title      string `gorm:"column:title" json:"title"`
	Img        string `gorm:"column:img" json:"img"`
	Address    string `gorm:"column:address" json:"address"`
	PlatformID int32  `gorm:"column:platform_id" json:"platform_id"`
}

// TableName StreamerOnline's table name
func (*StreamerOnline) TableName() string {
	return TableNameStreamerOnline
}
